---
update_db: false
backend: apt
operations:
  - remove:
      - "^live-*"
      - calamares
      - calamares-settings-ubuntu-common
      - calamares-settings-ubuntu-unity
      - ubiquity
      - ubiquity-frontend-gtk
      - ubiquity-frontend-kde
      - calamares-extensions
      - calamares-extensions-data
