---
dontChroot: true
timeout: 30
script:
    - command: sed -i -E -e '/^[[:space:]]*autologin-user[[:space:]=]/d' -e '/^[[:space:]]*autologin-session[[:space:]=]/d' -e '/^[[:space:]]*autologin-user-timeout[[:space:]=]/d' ${ROOT}/etc/lightdm/lightdm.conf; true
      timeout: 30
