---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    4
    requiredRam:        0.5
    internetCheckUrl:   https://connectivitycheck.gstatic.com/generate_204

    check:
        - storage
        - ram
        - root
    required:
        - root
        - storage
        - ram

geoip:
    style:  "none"
    url:    "https://geoip.ubuntu.com/lookup"
    selector: "CountryCode"
