---
modules-search: [ local ]

instances:
- id: before_bootloader_mkdirs
  module: contextualprocess
  config: before_bootloader_mkdirs_context.conf
- id: logs
  module: shellprocess
  config: shellprocess_logs.conf
- id: cleanlightdm
  module: shellprocess
  config: shellprocess_cleanlightdm.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - contextualprocess@before_bootloader_mkdirs
  - initramfscfg
  - initramfs
  - grubcfg
  - bootloader
  - packages
  - shellprocess@cleanlightdm
  - shellprocess@logs
  - umount
- show:
  - finished

branding: carpentian
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
